## **Data Loading and Reading:**

In [4]:
import pandas as pd
data=pd.read_csv("C:\\Users\\SYS\\Desktop\\ai lab 9\\student_burnout_dataset (1).csv")
data

,student_id,age,gender,study_hours_per_day,sleep_hours,social_media_hours,attendance_percentage,assignment_completion_rate,stress_level,burnout_level,exam_score
0,1,24,Male,4.5,5.9,3.0,86.5,45.5,6,Medium,42.1
1,2,21,Male,5.3,5.7,4.5,59.2,43.6,1,Low,38.3
2,3,22,Male,8.7,4.9,3.4,67.3,76.3,6,Medium,52.6
3,4,24,Male,4.1,7.0,0.5,83.2,98.0,4,Low,44.9
4,5,20,Female,8.8,6.4,1.1,74.1,70.2,4,Low,66.2
...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,22,Female,8.7,7.3,5.3,66.4,97.1,7,Medium,50.0
4996,4997,23,Male,9.1,4.9,0.3,86.3,84.9,4,Low,62.2
4997,4998,20,Female,9.5,4.3,1.8,96.2,41.2,1,Low,81.6
4998,4999,19,Female,4.6,7.4,2.7,81.9,64.1,9,Medium,15.3
4999,5000,21,Male,3.0,5.3,1.0,97.6,55.4,2,Low,39.5

## **Data Exploration:**

In [5]:
data.head()

,student_id,age,gender,study_hours_per_day,sleep_hours,social_media_hours,attendance_percentage,assignment_completion_rate,stress_level,burnout_level,exam_score
0,1,24,Male,4.5,5.9,3.0,86.5,45.5,6,Medium,42.1
1,2,21,Male,5.3,5.7,4.5,59.2,43.6,1,Low,38.3
2,3,22,Male,8.7,4.9,3.4,67.3,76.3,6,Medium,52.6
3,4,24,Male,4.1,7.0,0.5,83.2,98.0,4,Low,44.9
4,5,20,Female,8.8,6.4,1.1,74.1,70.2,4,Low,66.2

In [6]:
data.tail()

,student_id,age,gender,study_hours_per_day,sleep_hours,social_media_hours,attendance_percentage,assignment_completion_rate,stress_level,burnout_level,exam_score
4995,4996,22,Female,8.7,7.3,5.3,66.4,97.1,7,Medium,50.0
4996,4997,23,Male,9.1,4.9,0.3,86.3,84.9,4,Low,62.2
4997,4998,20,Female,9.5,4.3,1.8,96.2,41.2,1,Low,81.6
4998,4999,19,Female,4.6,7.4,2.7,81.9,64.1,9,Medium,15.3
4999,5000,21,Male,3.0,5.3,1.0,97.6,55.4,2,Low,39.5

In [7]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   student_id                  5000 non-null   int64
 1   age                         5000 non-null   int64
 2   gender                      5000 non-null   str
 3   study_hours_per_day         5000 non-null   float64
 4   sleep_hours                 5000 non-null   float64
 5   social_media_hours          5000 non-null   float64
 6   attendance_percentage       5000 non-null   float64
 7   assignment_completion_rate  5000 non-null   float64
 8   stress_level                5000 non-null   int64
 9   burnout_level               5000 non-null   str
 10  exam_score                  5000 non-null   float64
dtypes: float64(6), int64(3), str(2)
memory usage: 429.8 KB

In [8]:
print('rows: ', data.shape[0])
print('columns: ', data.shape[1])

rows:  5000
columns:  11

In [9]:
data.isnull().sum()

student_id                    0
age                           0
gender                        0
study_hours_per_day           0
sleep_hours                   0
social_media_hours            0
attendance_percentage         0
assignment_completion_rate    0
stress_level                  0
burnout_level                 0
exam_score                    0
dtype: int64

In [10]:
Dataset = data.fillna(data.mean)
Dataset = data.fillna(data.median)
Dataset = data.fillna(data.mode())